name: Gerar Animação da Cobrinha

on:
  # Executa automaticamente a cada 24 horas
  schedule:
    - cron: "0 0 * * *" 
  
  # Permite rodar o script manualmente a qualquer momento
  workflow_dispatch:
  
  # Executa toda vez que for feito um push na branch main
  push:
    branches:
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Gerar os arquivos SVG da cobrinha
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - name: Enviar a imagem para a branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
